// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLHX6XJrSU_ulc5YWwMPDje-wq2c8T0SQ',
    appId: '1:1012069754938:web:55d9d6e0711159538bad03',
    messagingSenderId: '1012069754938',
    projectId: 'appixo',
    authDomain: 'appixo.firebaseapp.com',
    storageBucket: 'appixo.appspot.com',
    measurementId: 'G-DWWVEHEWZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjESwnZAqWTwFP_U2KjnSfuF_T-hRc2pY',
    appId: '1:1012069754938:android:5a13caaa264eb1c28bad03',
    messagingSenderId: '1012069754938',
    projectId: 'appixo',
    storageBucket: 'appixo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwsLCabPSfnXi7Mq2JV3vzl4Xjl1nMB1Y',
    appId: '1:1012069754938:ios:a7547a8da43f417e8bad03',
    messagingSenderId: '1012069754938',
    projectId: 'appixo',
    storageBucket: 'appixo.appspot.com',
    androidClientId: '1012069754938-0gf90igbsfhcfpdbhj1l7bv7lhlm03oa.apps.googleusercontent.com',
    iosClientId: '1012069754938-63eic9g0j3q7t94g0jpqm8d5b9ufhj1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.manishsahu.appixo.admin.appixoadmin',
  );
}
